name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    types: [closed]

jobs:
  version-bump:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Determine version increment from branch name
        id: determine-bump
        run: |
          BRANCH_NAME="${{ github.head_ref }}"
          VERSION_TYPE="patch" # Default to patch
          if [[ "$BRANCH_NAME" =~ major\/ ]]; then
            VERSION_TYPE="major"
          elif [[ "$BRANCH_NAME" =~ minor\/ ]]; then
            VERSION_TYPE="minor"
          fi
          echo "::set-output name=version-type::$VERSION_TYPE"
          
      - name: Install bump2version
        run: pip install bump2version

      - name: Configure Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Bump version
        run: bump2version ${{ steps.determine-bump.outputs.version-type }}

      - name: Push version bump commit
        run: |
          git push --follow-tags
